version: '3'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./src:/src
  php:
    build:
      context: .
      dockerfile: config/Dockerfile
    volumes:
      - ./src:/src
  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_DATABASE: 'blog_db'
      MYSQL_TCP_PORT: 3306
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysqldata: {}